Repository Aloneking789/elite, pull requests merged in 2024-10, with the labels that each got.

#2 README.md
  README.md
Labels: Hacktoberfest 2024

#3 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: good first issue, Hacktoberfest 2024

#4 Create CODE_OF_CONDUCT.MD
  CODE_OF_CONDUCT.MD
Labels: Hacktoberfest 2024

#12 dark mode feature added
  src/App.jsx
  src/DarkModeContext.jsx
  src/DarkModeToggle.jsx
  src/components/About/About.jsx
  src/components/Contact/Contact.jsx
  src/components/Footer/Footer.jsx
  src/components/Github/Github.jsx
  src/components/Header/Header.jsx
  src/components/Home/Home.jsx
  src/index.css
  src/main.jsx
  tailwind.config.js
Labels: Hacktoberfest 2024, gssoc-ext, level2

#25 Added Member Page
  src/components/Header/Header.jsx
  src/components/Members/Members.jsx
  src/main.jsx
Labels: Hacktoberfest 2024
